name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name "R2-D2 [bot]"
          git config user.email "artoo-detoo@devstream.in"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        wirh:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Push docs to gh-pages branch
        run: uv run mkdocs gh-deploy